on:
  push:
    branches: [ main ]
jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - 
        run: mkdir downloads

      - name: Step 2 - 
        run: |
          cd downloads
          echo 'alpha' > alpha.html
          echo 'bravo' > bravo.html
          echo 'charlie' > charlie.html
          cd ..

      - name: Step 3
        uses: actions/upload-artifact@v4
        with: 
          name: asset-for-download
          path: downloads
